### ISSUE TITLE
Two or more players with activated magnets can dupe item

### ISSUE THREAD

**Issue by takarabako** [FantasyTeddy/QuantumFlux#12]
**What is happening**
When two or more players with activated magnets are near each other, items dropped near them will get picked by both of them, results in duping the dropped items.

**How to reproduce**
1. Tell two players go near each other and activate their magnets.
2. One of them drop an item of any kind on the ground.

**Expected behavior**
One of the player gets the item, not both.

---
*Version:* quantumflux-1.12.2-2.0.16
*Mod pack:* FTB Presents Stoneblock 2

Checking itemtoGet.isDead [here](https://github.com/FantasyTeddy/QuantumFlux/blob/master/src/main/java/jotato/quantumflux/items/ItemMagnet.java#L70) should be enough to fix this. If the item is already picked up by someone, setDead() will be called.

**Comment by Yunus1903** [comment]
I can confirm, found out about it in the StoneBlock 2 modpack

**Comment by FantasyTeddy** [comment]
Thank you for reporting this issue and even providing a solution. I made your suggested changes and released a new version. Can you please check if the bug is gone?
