### ISSUE TITLE
[Bug]The game crash on sturtup

### ISSUE THREAD

**Issue by HurtsAsHell** [FantasyTeddy/QuantumFlux#14]
**What is happening**
The game crash on sturtup

**How to reproduce**
1. IDK
2. The game crash on sturtup
3. [Crash Report with all installed mod](https://pastebin.com/y8YQjvyX)

---
*Version:* [1.12.2-2.0.17]
*Mod pack:* [Custom Modpack]

if you want i can give you the forge version

_I don't know if the problem is of your mod, i read "Caught exception from QuantumFlux (quantumflux)" and i think the problem is of your mod_

**Sorry for my bad translation**

**Comment by FantasyTeddy** [comment]
Thank you for reporting this major issue, I should have tested this version (2.0.17) after uploading it.
I made a mistake during building and ended up with a bad .jar. I re-uploaded version 2.0.17 which should now be working. Can you check if this is the case?

**Comment by HurtsAsHell** [comment]
as soon as I program the modpack i test it

**Comment by HurtsAsHell** [comment]
Okay, i'm testing now and for the moment the modpack doesn't crash

**Comment by FantasyTeddy** [comment]
Great, thank you for your feedback.
