### ISSUE TITLE
[BUG] RF Entangler just deletes power.

### ISSUE THREAD

**Issue by TheUnderTaker11** [FantasyTeddy/QuantumFlux#16]
**What is happening**
RF Entangler does nothing but gobble up power.       
Tested with Mekanism, EnderIO, RFTools, and ExtraUtilities.       
[Video Link with my testing here for proof](https://www.youtube.com/watch?v=4c-gF2_LWaY&feature=youtu.be)        
I have not placed any exciters or anything like that, only the two cells you see in the video in my inventory.
**How to reproduce**
1. Place entangler
2. Try and put power into it.
3. Watch as all your power fades away.

**Expected behavior**
It to work lol.

---
*Version:* [1.12.2-2.0.17]
*Mod pack:* [Custom]

**Comment by FantasyTeddy** [comment]
Thank you for this bug report.
It should be fixed in the latest version (2.0.18)
Could you verify that it is now working?
