### ISSUE TITLE
Willing to add my magnet mod's code to this magnet.

### ISSUE THREAD

**Issue by TheUnderTaker11** [FantasyTeddy/QuantumFlux#18]
**Feature context**
I will make the magnet work as a bauble, will add an anti-magnet block to cancel out the suction for items above and below it.
Also might as well add the chat message telling you if the magnet has been enabled or disabled.

**Reasoning**
Will overall greatly improve the magnet from this mod. As the magnet stands it's not really that practical since there are no blocks to cancel out the magnet.

My main question is if you want me to add that code from my mod over, cause it won't take too long for me to make a PR with my stuff added. (When I get around to actually doing it.)

**Comment by FantasyTeddy** [comment]
Thank you very much for your offer. I would gladly accept any PR you issue for this.

This would be my wish-list:

- Making the magnet work as a bauble would be great (in any slot).
- I don't really like the idea of adding an anti-magnet block to this mod... using a mod like [Demagnetize](https://minecraft.curseforge.com/projects/demagnetize) is my preferred way of achieving this.
- Feel free to add a chat message for enabling/disabling the magnet.

**Comment by TheUnderTaker11** [comment]
Was not aware of this mods existence, I would highly suggest linking to
that mod on your curse page or somehow telling people who use your magnet
about it! Is an awesome mod I've never seen before, and it is honestly
needed to make your magnet practical.
