### ISSUE TITLE
Crash without Redstone Flux

### ISSUE THREAD

**Issue by Lykrast** [FantasyTeddy/QuantumFlux#3]
*Version:* 1.12.2-2.0.13

*Mod pack:* none

*Summary:* Game crashes when Redstone Flux is not installed, instead of displaying an error telling the user the mod needs Redstone Flux.

____

Launching the game without Redstone Flux installed causes the game to crash with [the following error](https://gist.github.com/Lykrast/c90de99f1a9157bb2ffd65a8fbd12d11).

To prevent that, Redstone Flux should be specified as a dependency in the Mod annotation to replace this crash with the forge screen warning about a missing dependency.

It would also be nice to put Redstone Flux as a Required Library on Curseforge so people are aware they need it and so that the Twitch Launcher automatically installs it with the mod.

**Comment by FantasyTeddy** [comment]
Thanks I was not aware of that. I will try to fix this in an upcoming release.

**Comment by kragnoth** [comment]
If you switch over to also supporting forge energy (if you don't already) that would fix the issue I mentioned on the ftb reddit.

It seems that Immersive Engineering connectors aren't compatible with Quantum Flux machines.  This is usually due to one using RF and the other only using forge energy api calls.  Mekanism works as an inbetween for now.

**Comment by FantasyTeddy** [comment]
This is a great suggestion, I think I'm going to use the Forge energy system to fix this issue.

**Comment by FantasyTeddy** [comment]
I just released version 2.0.14 where this issue should be resolved. Redstone Flux is now a dependency on Curseforge as well.

@kragnoth: It would be great if you could test this new version to see if the machines are compatible with other mods like Immersive Engineering now (support for the forge energy system has been added).
