### ISSUE TITLE
Unlocalized item descriptions

### ISSUE THREAD

**Issue by Lykrast** [FantasyTeddy/QuantumFlux#4]
*Version:* 1.12.2-2.0.13

*Mod pack:* none

*Summary:* Several items have their description unlocalized.

____

The Quibit Crystal, Gold Casing, Amplification Crystal, Ender Crystal, Quantum Disk and the Advanced Circuit all have unlocalized descriptions.

![image](https://user-images.githubusercontent.com/8684850/42782624-c13a19ec-8949-11e8-8cc7-39a77b749002.png)

**Comment by FantasyTeddy** [comment]
The unlocalized descriptions have been removed in the newest version. Thank you for reporting!
