### ISSUE TITLE
Quantum Entropy Accelerator [1.12.2]

### ISSUE THREAD

**Issue by Cazadorsniper** [FantasyTeddy/QuantumFlux#5]
Submitting a bug report? Please fill out the form below the best you can.

*Version:* 1.12.2-2.0.13

*Mod pack:* Project Ozone 3 

*Summary:* 
Isn't suppose to have a GUI?
Crash if trying to force an item into it.
____

**What is happening** 
Crash when trying to force item into the machine with a hopper.
https://pastebin.com/cv4WJUmQ

Maybe a conflict with Foamfix not sure.

**How can I reproduce the problem?** 
Place hopper on top of the QEA then place any item in the hopper.

**Comment by FantasyTeddy** [comment]
The GUI of the Quantum Entropy Accelerator has been removed in an earlier version. But you are correct, you should at least be able to put items into it via hopper or similar.

At the moment I am not sure if the GUI should be added again, or if the QEA should be removed entirely.

**Comment by Cazadorsniper** [comment]
I like the QEA, also Ender IO item conduits  do not connect to it.

**Comment by FantasyTeddy** [comment]
The issues you mentioned should be fixed now in version 2.0.15 and the QEA also got a new GUI.
