### ISSUE TITLE
Unable to remove recipes with cratftweaker

### ISSUE THREAD

**Issue by Thedrummonger** [FantasyTeddy/QuantumFlux#6]
After adding a script to remove some recipes in this mod with craftweaker, the recipes are still available when the game is loaded. The script is correct and does not show any errors, it seems that recipes may be loaded after craftweaker attempts to remove them. I have replicated this issue in a pack with only quantum flux, JEI and craftweaker.
---
quantumflux-1.12.2-2.0.14
CraftTweaker2-1.12-4.1.9
forge-14.23.4.2739

**Comment by FantasyTeddy** [comment]
I didn't test this, but I guess this was because I did not use the new recipe system (recipes are an asset now, who knew?!).
It should be fixed in the latest version. Feel free to reopen this issue if your issue still exists.
