### ISSUE TITLE
ZP Extractor max value and oregen config

### ISSUE THREAD

**Issue by dancc7t** [FantasyTeddy/QuantumFlux#8]
**Feature context**
Hello, i've almost finished my modpack after almost one year, this modpack uses biome-based dimension-whitelisted oregen for 100% of all ores, and changes over 1700 recipes (atm)

**Reasoning**
There are dimensions such as Twilight (just 1 ore generates in there), Hoanna (just 1 ore generates in there), Luna (just 1 ore generates in there), Aroma1997's (nothing generates in there), that require me to control oregen of all the ores, the only one left is Industrial Grade Graphite Ore, so it would be great if you can add a config option to enable/disable its generation.

QuantumFlux items/machines are in my modpack a mid-late gameplay, so i changed the recipes to be crafted not so early in the game, and with only a max 256RF/t, people might prefer to go solar instead of ZP. If you can double the max amount of energy it can produce to 512 then it will be more reasonable given the moment of the game. (My plan was it to produce 450RF/t  at bedrock layer).

Thanks.

**Comment by FantasyTeddy** [comment]
Thank you for your suggestion. I can definitely make the ore generation configurable.
I will also consider making the ZPE max output higher.
